from pydantic import BaseModel, Field
from typing import Optional

class EmailRequest(BaseModel):
    subject: str = Field(..., description="The subject of the customer email")
    body: str = Field(..., description="The main content of the customer email")
    customer_id: Optional[str] = Field(None, description="Optional customer identifier")

class EmailResponse(BaseModel):
    final_reply: str = Field(..., description="The finalized email reply generated by the agent or human")
    category: str = Field(..., description="The category the email was classified as")
    confidence_score: float = Field(..., description="Agent confidence score (0.0 to 1.0)")
    human_reviewed: bool = Field(..., description="True if a human reviewed the reply")
    follow_up_scheduled: bool = Field(..., description="True if a follow-up was scheduled")

# --- Agent Structured Outputs Schemas ---

class EmailCategory(BaseModel):
    """Schema for classifying the incoming email."""
    category: str = Field(
        ..., 
        description="The category of the email. e.g., 'billing', 'technical_support', 'general_inquiry', 'complaint'."
    )
    urgency: str = Field(
        ...,
        description="The urgency of the email: 'low', 'medium', or 'high'."
    )
    
class DraftResponse(BaseModel):
    """Schema for drafting the initial reply and routing prediction."""
    draft: str = Field(..., description="The structured draft response referencing the knowledge base info.")
    confidence: float = Field(..., description="Confidence score from 0.0 to 1.0 for the drafted response.")
    needs_human_review: bool = Field(
        ..., 
        description="Set to true if the query is extremely complex, emotional, or the confidence in the answer is low."
    )
